network_id: fedn-test-network

control:
  state: idle
  helper: keras_weights

statestore:
  type: MongoDB
  mongo_config:
    username: fedn_admin
    password: password
    host: 13.48.195.125
    port: 6534

storage:
  storage_type: S3
  storage_config:
    storage_hostname: 13.48.195.125
    storage_port: 9000
    storage_access_key: fedn_admin
    storage_secret_key: password
    storage_bucket: fedn-models
    context_bucket: fedn-context
    storage_secure_mode: False 